# Generated by Django 6.0.2 on 2026-02-26 10:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'Зручність', 'verbose_name_plural': 'Зручності'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Кімната', 'verbose_name_plural': 'Кімнати'},
        ),
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Доступно для бронювання'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ціна за ніч'),
        ),
    ]
