name: Django CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Загрузка кода (Checkout)
        uses: actions/checkout@v4

      - name: Запуск контейнеров через Docker Compose
        run: docker-compose up -d --build

      - name: Ожидание готовности сервера
        run: sleep 10

      - name: Запуск тестов (Pytest)
        run: docker-compose exec -T web pytest